version: '3.8'

services:
  diambra_webui:
    build: .
    ports:
      - "5000:5000"
      - "6006:6006"
    volumes:
      - ./app:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    stdin_open: true
    tty: true
